import type {
  Asset,
  DashboardData,
} from './store'

// ─── SEED_ASSETS ──────────────────────────────────────────────────────────────

export const SEED_ASSETS: Asset[] = [
  // 1) Centro Logístico Santiago Norte
  {
    id: 'asset_logistico_norte',
    name: 'Centro Logístico Santiago Norte',
    slug: 'centro-logistico-santiago-norte',
    type: 'last_mile_logistics',
    status: 'active',
    address: 'Av. Américo Vespucio 0800, Parque Industrial Norte',
    city: 'Santiago',
    region: 'Región Metropolitana',
    country: 'Chile',
    totalValue: 2_500_000_000,
    pricePerFraction: 250_000,
    totalFractions: 10_000,
    availableFractions: 3_200,
    minimumInvestment: 250_000,
    fundedPercentage: 68,
    annualYield: 13.8,
    projectedAppreciation: 4.2,
    totalProjectedReturn: 18.0,
    leaseStatus: 'leased',
    monthlyRent: 18_500_000,
    tenantName: 'LogiChile S.A.',
    totalArea: 12_500,
    units: 48,
    constructionYear: 2022,
    landUse: 'Industrial / Logístico',
    shortDescription:
      'Centro logístico de última milla en zona estratégica de Santiago con contrato de arriendo a 10 años.',
    fullDescription:
      'El Centro Logístico Santiago Norte es una propiedad industrial de última milla ubicada en una de las zonas de mayor crecimiento logístico de la Región Metropolitana. Cuenta con 12.500 m² de área útil distribuidos en 48 unidades modulares que se adaptan a las necesidades de empresas de comercio electrónico y distribución.\n\nLa propiedad está arrendada a LogiChile S.A. mediante un contrato de arriendo corporativo a 10 años con ajuste anual según IPC. La ubicación estratégica sobre la Américo Vespucio permite acceso directo a las principales rutas de distribución de la capital.\n\nEntre sus características se incluyen: docks de carga de nivel, sistema de suppression de incendios, cámaras de seguridad 24/7, estacionamiento para camiones y personal administrativo, y certificación LEED Silver en eficiencia energética.',
    highlights: JSON.stringify([
      'Contrato de arriendo a 10 años con ajuste IPC',
      'Ubicación estratégica sobre Américo Vespucio',
      '12.500 m² de área útil con 48 unidades modulares',
      'Certificación LEED Silver en eficiencia energética',
      'Sistema de suppression de incendios y seguridad 24/7',
      'Tenant blue-chip: LogiChile S.A.',
    ]),
    badge: 'Últimas Millas',
    operationalCostsPct: 3.0,
    images: [
      {
        id: 'img_ln_01',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=500&fit=crop',
        alt: 'Centro logístico moderno en Santiago',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_ln_02',
        url: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&h=500&fit=crop',
        alt: 'Interior del centro de distribución',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img_ln_03',
        url: 'https://images.unsplash.com/photo-1586953208270-767889db8665?w=800&h=500&fit=crop',
        alt: 'Docks de carga del centro logístico',
        sortOrder: 2,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_ln_01',
        title: 'Estudio de Tasa de Arriendo',
        documentType: 'tasacion',
        fileUrl: '/docs/asset_logistico_norte/tasacion.pdf',
        fileSize: 2_450_000,
      },
      {
        id: 'doc_ln_02',
        title: 'Contrato de Arriendo',
        documentType: 'contrato',
        fileUrl: '/docs/asset_logistico_norte/contrato.pdf',
        fileSize: 1_820_000,
      },
      {
        id: 'doc_ln_03',
        title: 'Informe de Ingeniería Estructural',
        documentType: 'informe',
        fileUrl: '/docs/asset_logistico_norte/ingenieria.pdf',
        fileSize: 5_300_000,
      },
      {
        id: 'doc_ln_04',
        title: 'Certificado LEED Silver',
        documentType: 'certificado',
        fileUrl: '/docs/asset_logistico_norte/leed.pdf',
        fileSize: 980_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_ln_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 222_000_000,
        operationalCost: 6_660_000,
        netIncome: 215_340_000,
        appreciation: 4.2,
        totalReturn: 18.0,
        cumulativeReturn: 18.0,
      },
      {
        id: 'cf_ln_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 230_664_000,
        operationalCost: 6_920_000,
        netIncome: 223_744_000,
        appreciation: 4.0,
        totalReturn: 17.8,
        cumulativeReturn: 36.2,
      },
      {
        id: 'cf_ln_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 239_501_120,
        operationalCost: 7_185_000,
        netIncome: 232_316_120,
        appreciation: 3.8,
        totalReturn: 17.6,
        cumulativeReturn: 54.5,
      },
      {
        id: 'cf_ln_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 248_511_666,
        operationalCost: 7_455_000,
        netIncome: 241_056_666,
        appreciation: 3.6,
        totalReturn: 17.4,
        cumulativeReturn: 72.7,
      },
      {
        id: 'cf_ln_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 257_697_132,
        operationalCost: 7_731_000,
        netIncome: 249_966_132,
        appreciation: 3.5,
        totalReturn: 17.3,
        cumulativeReturn: 90.8,
      },
    ],
    _count: { investments: 234 },
    createdAt: '2024-06-15T10:30:00.000Z',
    updatedAt: '2025-01-10T14:22:00.000Z',
  },

  // 2) Micro Data Center Valparaíso
  {
    id: 'asset_datacenter_vp',
    name: 'Micro Data Center Valparaíso',
    slug: 'micro-data-center-valparaiso',
    type: 'micro_datacenter',
    status: 'active',
    address: 'Pasaje Rodrigo de Araya 285, Barrio Industrial',
    city: 'Valparaíso',
    region: 'Valparaíso',
    country: 'Chile',
    totalValue: 925_000_000,
    pricePerFraction: 185_000,
    totalFractions: 5_000,
    availableFractions: 1_150,
    minimumInvestment: 185_000,
    fundedPercentage: 77,
    annualYield: 16.5,
    projectedAppreciation: 3.8,
    totalProjectedReturn: 20.3,
    leaseStatus: 'leased',
    monthlyRent: 9_200_000,
    tenantName: 'CloudSur Datacenters SpA',
    totalArea: 1_800,
    units: 12,
    constructionYear: 2023,
    landUse: 'Tecnológico / Infraestructura',
    shortDescription:
      'Micro data center de alta densidad en Valparaíso con contrato de arriendo a largo plazo.',
    fullDescription:
      'El Micro Data Center Valparaíso es una instalación tecnológica de alta densidad ubicada en el corazón del corredor tecnológico de la Región de Valparaíso. Diseñado para satisfacer la creciente demanda de servicios cloud en la zona, cuenta con 1.800 m² de área técnica distribuidos en 12 salas de servidores.\n\nLa propiedad está arrendada a CloudSur Datacenters SpA bajo un contrato de arriendo triple-net a 8 años con opción de renovación automática. El data center cuenta con certificación Tier II+, refrigeración free-cooling y alimentación dual de energía.\n\nLa inversión incluye acceso a reportes trimestrales de SLA, auditorías de seguridad física y lógica, y un comité técnico de monitoreo continuo.',
    highlights: JSON.stringify([
      'Contrato triple-net a 8 años con renovación automática',
      'Certificación Tier II+ de disponibilidad',
      'Refrigeración free-cooling — menor consumo energético',
      'Alimentación dual de energía con UPS redundante',
      'Reportes trimestrales de SLA y auditorías',
      'Tenant especializado: CloudSur Datacenters SpA',
    ]),
    badge: 'Alto Rendimiento',
    operationalCostsPct: 2.5,
    images: [
      {
        id: 'img_dc_01',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=500&fit=crop',
        alt: 'Data center con servidores iluminados',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_dc_02',
        url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=500&fit=crop',
        alt: 'Racks de servidores modernos',
        sortOrder: 1,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_dc_01',
        title: 'Certificación Tier II+',
        documentType: 'certificado',
        fileUrl: '/docs/asset_datacenter_vp/tier2plus.pdf',
        fileSize: 1_500_000,
      },
      {
        id: 'doc_dc_02',
        title: 'Informe de SLA Q4 2024',
        documentType: 'informe',
        fileUrl: '/docs/asset_datacenter_vp/sla-q4.pdf',
        fileSize: 3_200_000,
      },
      {
        id: 'doc_dc_03',
        title: 'Contrato de Arriendo',
        documentType: 'contrato',
        fileUrl: '/docs/asset_datacenter_vp/contrato.pdf',
        fileSize: 1_100_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_dc_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 110_400_000,
        operationalCost: 2_760_000,
        netIncome: 107_640_000,
        appreciation: 3.8,
        totalReturn: 20.3,
        cumulativeReturn: 20.3,
      },
      {
        id: 'cf_dc_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 113_112_000,
        operationalCost: 2_828_000,
        netIncome: 110_284_000,
        appreciation: 3.6,
        totalReturn: 20.1,
        cumulativeReturn: 40.8,
      },
      {
        id: 'cf_dc_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 115_879_440,
        operationalCost: 2_897_000,
        netIncome: 112_982_440,
        appreciation: 3.4,
        totalReturn: 19.9,
        cumulativeReturn: 61.5,
      },
      {
        id: 'cf_dc_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 118_703_329,
        operationalCost: 2_968_000,
        netIncome: 115_735_329,
        appreciation: 3.2,
        totalReturn: 19.7,
        cumulativeReturn: 82.0,
      },
      {
        id: 'cf_dc_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 121_584_908,
        operationalCost: 3_040_000,
        netIncome: 118_544_908,
        appreciation: 3.0,
        totalReturn: 19.5,
        cumulativeReturn: 102.3,
      },
    ],
    _count: { investments: 187 },
    createdAt: '2024-08-22T08:00:00.000Z',
    updatedAt: '2025-01-08T11:15:00.000Z',
  },

  // 3) Parque Solar Atacama III
  {
    id: 'asset_solar_atacama',
    name: 'Parque Solar Atacama III',
    slug: 'parque-solar-atacama-iii',
    type: 'solar_energy',
    status: 'active',
    address: 'Camino al Salar de Atacama km 12, Sector Coya Sur',
    city: 'Calama',
    region: 'Antofagasta',
    country: 'Chile',
    totalValue: 4_200_000_000,
    pricePerFraction: 520_000,
    totalFractions: 8_077,
    availableFractions: 2_400,
    minimumInvestment: 520_000,
    fundedPercentage: 70,
    annualYield: 14.2,
    projectedAppreciation: 3.0,
    totalProjectedReturn: 17.2,
    leaseStatus: 'leased',
    monthlyRent: 32_500_000,
    tenantName: 'AtacamaSolar Energía Ltda.',
    totalArea: 35_000,
    units: 4,
    constructionYear: 2023,
    landUse: 'Energía Renovable',
    shortDescription:
      'Parque solar de gran escala en el desierto de Atacama con PPA a 15 años y altos niveles de irradiación.',
    fullDescription:
      'El Parque Solar Atacama III es una instalación de generación fotovoltaica a gran escala ubicada en el desierto de Atacama, la zona con mayor irradiación solar del mundo. Con 35.000 m² de paneles solares de última generación, la planta tiene una capacidad instalada de 8 MW.\n\nLa energía generada se vende mediante un Power Purchase Agreement (PPA) a 15 años firmado con AtacamaSolar Energía Ltda. El contrato garantiza un flujo de ingresos estable y predecible, ajustado anualmente según la variación del costo de energía en la red eléctrica.\n\nEl activo incluye mantenimiento preventivo y correctivo cubierto por el fabricante de los paneles, seguros contra todo riesgo y un sistema de monitoreo remoto 24/7.',
    highlights: JSON.stringify([
      'PPA a 15 años con garantía de compra de energía',
      'Mayor irradiación solar del mundo (>2.500 kWh/m²/año)',
      'Capacidad instalada: 8 MW de generación limpia',
      'Mantenimiento cubierto por fabricante por 10 años',
      'Contribuye a bonos de carbono verificables',
      'Seguro contra todo riesgo incluido',
    ]),
    badge: 'Energía Limpia',
    operationalCostsPct: 2.0,
    images: [
      {
        id: 'img_sl_01',
        url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=500&fit=crop',
        alt: 'Paneles solares en el desierto de Atacama',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_sl_02',
        url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&h=500&fit=crop',
        alt: 'Vista aérea del parque solar',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img_sl_03',
        url: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=500&fit=crop',
        alt: 'Atardecer sobre paneles solares',
        sortOrder: 2,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_sl_01',
        title: 'PPA – Contrato de Compra de Energía',
        documentType: 'contrato',
        fileUrl: '/docs/asset_solar_atacama/ppa.pdf',
        fileSize: 2_800_000,
      },
      {
        id: 'doc_sl_02',
        title: 'Estudio de Irradiación Solar',
        documentType: 'estudio',
        fileUrl: '/docs/asset_solar_atacama/irradiacion.pdf',
        fileSize: 4_100_000,
      },
      {
        id: 'doc_sl_03',
        title: 'Certificado de Medición NCRE',
        documentType: 'certificado',
        fileUrl: '/docs/asset_solar_atacama/ncre.pdf',
        fileSize: 920_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_sl_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 390_000_000,
        operationalCost: 7_800_000,
        netIncome: 382_200_000,
        appreciation: 3.0,
        totalReturn: 17.2,
        cumulativeReturn: 17.2,
      },
      {
        id: 'cf_sl_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 399_000_000,
        operationalCost: 7_980_000,
        netIncome: 391_020_000,
        appreciation: 2.8,
        totalReturn: 17.0,
        cumulativeReturn: 34.6,
      },
      {
        id: 'cf_sl_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 408_120_000,
        operationalCost: 8_162_000,
        netIncome: 399_958_000,
        appreciation: 2.6,
        totalReturn: 16.8,
        cumulativeReturn: 52.2,
      },
      {
        id: 'cf_sl_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 417_362_400,
        operationalCost: 8_347_000,
        netIncome: 409_015_400,
        appreciation: 2.5,
        totalReturn: 16.7,
        cumulativeReturn: 69.5,
      },
      {
        id: 'cf_sl_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 426_726_648,
        operationalCost: 8_535_000,
        netIncome: 418_191_648,
        appreciation: 2.3,
        totalReturn: 16.5,
        cumulativeReturn: 86.8,
      },
    ],
    _count: { investments: 312 },
    createdAt: '2024-05-10T12:00:00.000Z',
    updatedAt: '2025-01-12T09:30:00.000Z',
  },

  // 4) Residencial Providencia Sky
  {
    id: 'asset_residencial_prov',
    name: 'Residencial Providencia Sky',
    slug: 'residencial-providencia-sky',
    type: 'real_estate',
    status: 'active',
    address: 'Av. Providencia 2340, Torre A, Piso 15',
    city: 'Santiago',
    region: 'Región Metropolitana',
    country: 'Chile',
    totalValue: 1_600_000_000,
    pricePerFraction: 160_000,
    totalFractions: 10_000,
    availableFractions: 4_500,
    minimumInvestment: 160_000,
    fundedPercentage: 55,
    annualYield: 11.5,
    projectedAppreciation: 5.5,
    totalProjectedReturn: 17.0,
    leaseStatus: 'leased',
    monthlyRent: 12_800_000,
    tenantName: 'Providencia Rent SpA',
    totalArea: 4_200,
    units: 24,
    constructionYear: 2021,
    landUse: 'Residencial / Uso Mixto',
    shortDescription:
      'Torre residencial de lujo en Providencia con arriendo corporativo y alto potencial de plusvalía.',
    fullDescription:
      'Residencial Providencia Sky es una torre de 18 pisos ubicada en una de las avenidas más emblemáticas de Santiago. Las 24 unidades residenciales de alta gama incluyen departamentos de 2 y 3 dormitorios con acabados premium y terrazas con vista panorámica.\n\nLa propiedad está arrendada en su totalidad a Providencia Rent SpA, que opera las unidades como arriendos corporativos de mediana y larga estadía. El contrato de arriendo maestro tiene una vigencia de 5 años con renovación automática.\n\nLa ubicación en el corazón de Providencia garantiza un alto potencial de plusvalía, con un crecimiento promedio del sector de 5.5% anual en los últimos 3 años.',
    highlights: JSON.stringify([
      'Ubicación premium en Av. Providencia — sector de mayor plusvalía',
      'Arriendo corporativo maestro a 5 años con renovación automática',
      '24 unidades de alta gama con acabados premium',
      'Crecimiento de plusvalía histórico: 5.5% anual',
      'Cercanía a metro Pedro Aguirre Cerda y servicios',
      'Gimnasio, rooftop y estacionamientos subterráneos',
    ]),
    badge: 'Plusvalía Premium',
    operationalCostsPct: 3.5,
    images: [
      {
        id: 'img_rp_01',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=500&fit=crop',
        alt: 'Torre residencial moderna en Santiago',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_rp_02',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=500&fit=crop',
        alt: 'Interior departamento de lujo',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img_rp_03',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=500&fit=crop',
        alt: 'Vista panorámica desde la torre',
        sortOrder: 2,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_rp_01',
        title: 'Tasación Comercial Actualizada',
        documentType: 'tasacion',
        fileUrl: '/docs/asset_residencial_prov/tasacion.pdf',
        fileSize: 1_800_000,
      },
      {
        id: 'doc_rp_02',
        title: 'Contrato de Arriendo Maestro',
        documentType: 'contrato',
        fileUrl: '/docs/asset_residencial_prov/contrato.pdf',
        fileSize: 1_350_000,
      },
      {
        id: 'doc_rp_03',
        title: 'Informe de Plusvalía del Sector',
        documentType: 'informe',
        fileUrl: '/docs/asset_residencial_prov/plusvalia.pdf',
        fileSize: 2_900_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_rp_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 153_600_000,
        operationalCost: 5_376_000,
        netIncome: 148_224_000,
        appreciation: 5.5,
        totalReturn: 17.0,
        cumulativeReturn: 17.0,
      },
      {
        id: 'cf_rp_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 158_208_000,
        operationalCost: 5_537_000,
        netIncome: 152_671_000,
        appreciation: 5.2,
        totalReturn: 16.7,
        cumulativeReturn: 34.0,
      },
      {
        id: 'cf_rp_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 162_954_240,
        operationalCost: 5_703_000,
        netIncome: 157_251_240,
        appreciation: 5.0,
        totalReturn: 16.5,
        cumulativeReturn: 51.3,
      },
      {
        id: 'cf_rp_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 167_842_867,
        operationalCost: 5_875_000,
        netIncome: 161_967_867,
        appreciation: 4.8,
        totalReturn: 16.3,
        cumulativeReturn: 68.4,
      },
      {
        id: 'cf_rp_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 172_878_153,
        operationalCost: 6_051_000,
        netIncome: 166_827_153,
        appreciation: 4.5,
        totalReturn: 16.0,
        cumulativeReturn: 85.4,
      },
    ],
    _count: { investments: 156 },
    createdAt: '2024-09-05T16:00:00.000Z',
    updatedAt: '2025-01-11T10:45:00.000Z',
  },

  // 5) Complejo Minero Atacama Norte
  {
    id: 'asset_minero_atacama',
    name: 'Complejo Minero Atacama Norte',
    slug: 'complejo-minero-atacama-norte',
    type: 'mining',
    status: 'active',
    address: 'Sector Minero Sierra Gorda, Concesión Minera SG-2048',
    city: 'Sierra Gorda',
    region: 'Antofagasta',
    country: 'Chile',
    totalValue: 6_800_000_000,
    pricePerFraction: 850_000,
    totalFractions: 8_000,
    availableFractions: 1_800,
    minimumInvestment: 850_000,
    fundedPercentage: 78,
    annualYield: 15.8,
    projectedAppreciation: 2.5,
    totalProjectedReturn: 18.3,
    leaseStatus: 'leased',
    monthlyRent: 55_200_000,
    tenantName: 'MineraAtacama SpA',
    totalArea: 120_000,
    units: 2,
    constructionYear: 2020,
    landUse: 'Minero / Extractivo',
    shortDescription:
      'Complejo minero de cobre en Antofagasta con derechos de explotación a 20 años y royalties crecientes.',
    fullDescription:
      'El Complejo Minero Atacama Norte comprende una concesión minera de cobre de 120 hectáreas ubicada en Sierra Gorda, una de las zonas de mayor producción cuprífera del mundo. La concesión tiene derechos de explotación vigentes por 20 años.\n\nLa propiedad está arrendada a MineraAtacama SpA, empresa con más de 15 años de operación en la zona. El contrato incluye royalties variables ligados al precio del cobre en la Bolsa de Metales de Londres (LME), lo que permite capturar alza en los precios del commodity.\n\nLa inversión ofrece una combinación única de ingresos por arriendo plus royalties, con un flujo de caja que históricamente ha superado las proyecciones conservadoras.',
    highlights: JSON.stringify([
      'Derechos de explotación vigentes por 20 años',
      'Royalties variables ligados al precio del cobre (LME)',
      '120 hectáreas en zona de mayor producción cuprífera del mundo',
      'Tenant con 15+ años de operación en la zona',
      'Ingresos duales: arriendo + royalties sobre producción',
      'Estudio geológico independiente disponible',
    ]),
    badge: 'Royalties Cobre',
    operationalCostsPct: 2.0,
    images: [
      {
        id: 'img_mn_01',
        url: 'https://images.unsplash.com/photo-1599894019798-7b8e3f888a0e?w=800&h=500&fit=crop',
        alt: 'Operación minera en el desierto de Atacama',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_mn_02',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop',
        alt: 'Vista del complejo minero a cielo abierto',
        sortOrder: 1,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_mn_01',
        title: 'Derechos de Concesión Minera',
        documentType: 'legal',
        fileUrl: '/docs/asset_minero_atacama/concesion.pdf',
        fileSize: 3_400_000,
      },
      {
        id: 'doc_mn_02',
        title: 'Estudio Geológico Independiente',
        documentType: 'estudio',
        fileUrl: '/docs/asset_minero_atacama/geologia.pdf',
        fileSize: 8_200_000,
      },
      {
        id: 'doc_mn_03',
        title: 'Contrato de Arriendo con Royalties',
        documentType: 'contrato',
        fileUrl: '/docs/asset_minero_atacama/contrato.pdf',
        fileSize: 2_100_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_mn_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 662_400_000,
        operationalCost: 13_248_000,
        netIncome: 649_152_000,
        appreciation: 2.5,
        totalReturn: 18.3,
        cumulativeReturn: 18.3,
      },
      {
        id: 'cf_mn_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 678_888_000,
        operationalCost: 13_578_000,
        netIncome: 665_310_000,
        appreciation: 2.4,
        totalReturn: 18.2,
        cumulativeReturn: 37.1,
      },
      {
        id: 'cf_mn_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 695_760_120,
        operationalCost: 13_915_000,
        netIncome: 681_845_120,
        appreciation: 2.3,
        totalReturn: 18.1,
        cumulativeReturn: 55.9,
      },
      {
        id: 'cf_mn_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 713_027_723,
        operationalCost: 14_261_000,
        netIncome: 698_766_723,
        appreciation: 2.2,
        totalReturn: 18.0,
        cumulativeReturn: 74.6,
      },
      {
        id: 'cf_mn_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 730_700_420,
        operationalCost: 14_614_000,
        netIncome: 716_086_420,
        appreciation: 2.0,
        totalReturn: 17.8,
        cumulativeReturn: 93.3,
      },
    ],
    _count: { investments: 445 },
    createdAt: '2024-03-20T09:00:00.000Z',
    updatedAt: '2025-01-13T16:00:00.000Z',
  },

  // 6) Bodega E-Commerce Maipú Hub
  {
    id: 'asset_ecommerce_maipu',
    name: 'Bodega E-Commerce Maipú Hub',
    slug: 'bodega-e-commerce-maipu-hub',
    type: 'last_mile_logistics',
    status: 'active',
    address: 'Av. Pajaritos 4820, Zona Industrial Maipú',
    city: 'Santiago',
    region: 'Región Metropolitana',
    country: 'Chile',
    totalValue: 1_200_000_000,
    pricePerFraction: 120_000,
    totalFractions: 10_000,
    availableFractions: 6_200,
    minimumInvestment: 120_000,
    fundedPercentage: 38,
    annualYield: 12.5,
    projectedAppreciation: 4.8,
    totalProjectedReturn: 17.3,
    leaseStatus: 'leased',
    monthlyRent: 8_200_000,
    tenantName: 'MercadoExpress Chile SpA',
    totalArea: 6_800,
    units: 32,
    constructionYear: 2024,
    landUse: 'Industrial / Logístico',
    shortDescription:
      'Bodega de fulfillment e-commerce en Maipú con contrato de arriendo a 7 años — acceso desde $120.000.',
    fullDescription:
      'La Bodega E-Commerce Maipú Hub es una instalación de fulfillment diseñada específicamente para el comercio electrónico. Con 6.800 m² de área útil distribuidos en 32 módulos de almacenamiento y despacho, la propiedad atiende la creciente demanda logística del e-commerce en Chile.\n\nLa propiedad está arrendada a MercadoExpress Chile SpA, uno de los marketplaces de mayor crecimiento en el país. El contrato de arriendo a 7 años incluye cláusulas de ajuste anual y un mecanismo de participación en la productividad del centro.\n\nEste activo es ideal para inversores que buscan entrar al mercado de inversión fraccionaria desde un monto accesible, con una proyección de retorno total de 17.3% anual combinando yield y plusvalía.',
    highlights: JSON.stringify([
      'Inversión mínima accesible desde $120.000 CLP',
      'Contrato de arriendo a 7 años con ajuste anual',
      'Diseñada específicamente para fulfillment e-commerce',
      '32 módulos de almacenamiento y despacho',
      'Tenant de alto crecimiento: MercadoExpress Chile SpA',
      'Zona de Maipú con fuerte demanda logística',
    ]),
    badge: 'Accesible',
    operationalCostsPct: 3.0,
    images: [
      {
        id: 'img_ec_01',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&h=500&fit=crop',
        alt: 'Bodega logística moderna',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img_ec_02',
        url: 'https://images.unsplash.com/photo-1565891741441-64926e441838?w=800&h=500&fit=crop',
        alt: 'Interior de bodega de fulfillment',
        sortOrder: 1,
        isCover: false,
      },
    ],
    documents: [
      {
        id: 'doc_ec_01',
        title: 'Tasación Comercial',
        documentType: 'tasacion',
        fileUrl: '/docs/asset_ecommerce_maipu/tasacion.pdf',
        fileSize: 1_600_000,
      },
      {
        id: 'doc_ec_02',
        title: 'Contrato de Arriendo',
        documentType: 'contrato',
        fileUrl: '/docs/asset_ecommerce_maipu/contrato.pdf',
        fileSize: 1_200_000,
      },
      {
        id: 'doc_ec_03',
        title: 'Plano Arquitectónico Aprobado',
        documentType: 'plano',
        fileUrl: '/docs/asset_ecommerce_maipu/plano.pdf',
        fileSize: 4_500_000,
      },
    ],
    cashFlowProjections: [
      {
        id: 'cf_ec_01',
        period: 'Año 1',
        periodType: 'annual',
        grossIncome: 98_400_000,
        operationalCost: 2_952_000,
        netIncome: 95_448_000,
        appreciation: 4.8,
        totalReturn: 17.3,
        cumulativeReturn: 17.3,
      },
      {
        id: 'cf_ec_02',
        period: 'Año 2',
        periodType: 'annual',
        grossIncome: 101_352_000,
        operationalCost: 3_041_000,
        netIncome: 98_311_000,
        appreciation: 4.6,
        totalReturn: 17.1,
        cumulativeReturn: 34.8,
      },
      {
        id: 'cf_ec_03',
        period: 'Año 3',
        periodType: 'annual',
        grossIncome: 104_392_560,
        operationalCost: 3_132_000,
        netIncome: 101_260_560,
        appreciation: 4.4,
        totalReturn: 16.9,
        cumulativeReturn: 52.4,
      },
      {
        id: 'cf_ec_04',
        period: 'Año 4',
        periodType: 'annual',
        grossIncome: 107_524_336,
        operationalCost: 3.226_000,
        netIncome: 104_298_336,
        appreciation: 4.2,
        totalReturn: 16.7,
        cumulativeReturn: 69.8,
      },
      {
        id: 'cf_ec_05',
        period: 'Año 5',
        periodType: 'annual',
        grossIncome: 110_750_066,
        operationalCost: 3.323_000,
        netIncome: 107_427_066,
        appreciation: 4.0,
        totalReturn: 16.5,
        cumulativeReturn: 87.1,
      },
    ],
    _count: { investments: 89 },
    createdAt: '2024-11-01T14:30:00.000Z',
    updatedAt: '2025-01-14T08:00:00.000Z',
  },
]

// ─── SEED_DASHBOARD_DATA ──────────────────────────────────────────────────────

export const SEED_DASHBOARD_DATA: DashboardData = {
  user: {
    id: 'usr_demo_001',
    name: 'María González',
    email: 'maria@example.com',
    role: 'investor',
    kycStatus: 'verified',
    balance: 4_850_000,
    totalInvested: 12_750_000,
    totalEarnings: 1_832_500,
  },

  investments: [
    {
      id: 'inv_001',
      userId: 'usr_demo_001',
      assetId: 'asset_logistico_norte',
      quantity: 10,
      pricePerUnit: 250_000,
      totalAmount: 2_500_000,
      status: 'active',
      completedAt: '2024-07-10T14:30:00.000Z',
      createdAt: '2024-07-08T09:15:00.000Z',
      updatedAt: '2024-07-10T14:30:00.000Z',
      asset: {
        id: 'asset_logistico_norte',
        name: 'Centro Logístico Santiago Norte',
        type: 'last_mile_logistics',
        status: 'active',
        pricePerFraction: 250_000,
        annualYield: 13.8,
        images: [
          {
            id: 'img_ln_01',
            url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop',
            alt: 'Centro logístico moderno en Santiago',
            sortOrder: 0,
            isCover: true,
          },
        ],
      },
    },
    {
      id: 'inv_002',
      userId: 'usr_demo_001',
      assetId: 'asset_datacenter_vp',
      quantity: 25,
      pricePerUnit: 185_000,
      totalAmount: 4_625_000,
      status: 'active',
      completedAt: '2024-09-05T11:00:00.000Z',
      createdAt: '2024-09-02T16:20:00.000Z',
      updatedAt: '2024-09-05T11:00:00.000Z',
      asset: {
        id: 'asset_datacenter_vp',
        name: 'Micro Data Center Valparaíso',
        type: 'micro_datacenter',
        status: 'active',
        pricePerFraction: 185_000,
        annualYield: 16.5,
        images: [
          {
            id: 'img_dc_01',
            url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=300&fit=crop',
            alt: 'Data center con servidores iluminados',
            sortOrder: 0,
            isCover: true,
          },
        ],
      },
    },
    {
      id: 'inv_003',
      userId: 'usr_demo_001',
      assetId: 'asset_ecommerce_maipu',
      quantity: 47,
      pricePerUnit: 120_000,
      totalAmount: 5_640_000,
      status: 'active',
      completedAt: '2024-11-15T10:45:00.000Z',
      createdAt: '2024-11-12T08:30:00.000Z',
      updatedAt: '2024-11-15T10:45:00.000Z',
      asset: {
        id: 'asset_ecommerce_maipu',
        name: 'Bodega E-Commerce Maipú Hub',
        type: 'last_mile_logistics',
        status: 'active',
        pricePerFraction: 120_000,
        annualYield: 12.5,
        images: [
          {
            id: 'img_ec_01',
            url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop',
            alt: 'Bodega logística moderna',
            sortOrder: 0,
            isCover: true,
          },
        ],
      },
    },
  ],

  transactions: [
    {
      id: 'tx_001',
      type: 'deposit',
      amount: 5_000_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Depósito inicial via transferencia bancaria',
      createdAt: '2024-07-05T10:00:00.000Z',
    },
    {
      id: 'tx_002',
      type: 'purchase',
      amount: 2_500_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Compra de 10 fracciones – Centro Logístico Santiago Norte',
      createdAt: '2024-07-08T09:15:00.000Z',
    },
    {
      id: 'tx_003',
      type: 'deposit',
      amount: 5_000_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Depósito via transferencia bancaria',
      createdAt: '2024-08-28T14:30:00.000Z',
    },
    {
      id: 'tx_004',
      type: 'purchase',
      amount: 4_625_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Compra de 25 fracciones – Micro Data Center Valparaíso',
      createdAt: '2024-09-02T16:20:00.000Z',
    },
    {
      id: 'tx_005',
      type: 'dividend',
      amount: 86_250,
      currency: 'CLP',
      status: 'completed',
      description: 'Dividendo Q3 2024 – Centro Logístico Santiago Norte',
      createdAt: '2024-10-01T08:00:00.000Z',
    },
    {
      id: 'tx_006',
      type: 'dividend',
      amount: 191_094,
      currency: 'CLP',
      status: 'completed',
      description: 'Dividendo Q4 2024 – Micro Data Center Valparaíso',
      createdAt: '2024-12-01T08:00:00.000Z',
    },
    {
      id: 'tx_007',
      type: 'deposit',
      amount: 6_000_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Depósito via transferencia bancaria',
      createdAt: '2024-11-10T09:00:00.000Z',
    },
    {
      id: 'tx_008',
      type: 'purchase',
      amount: 5_640_000,
      currency: 'CLP',
      status: 'completed',
      description: 'Compra de 47 fracciones – Bodega E-Commerce Maipú Hub',
      createdAt: '2024-11-12T08:30:00.000Z',
    },
    {
      id: 'tx_009',
      type: 'dividend',
      amount: 70_500,
      currency: 'CLP',
      status: 'pending',
      description: 'Dividendo Q1 2025 – Bodega E-Commerce Maipú Hub',
      createdAt: '2025-01-15T08:00:00.000Z',
    },
    {
      id: 'tx_010',
      type: 'dividend',
      amount: 86_250,
      currency: 'CLP',
      status: 'completed',
      description: 'Dividendo Q1 2025 – Centro Logístico Santiago Norte',
      createdAt: '2025-01-15T08:00:00.000Z',
    },
  ],

  dividendPayments: [
    {
      id: 'div_001',
      amount: 86_250,
      perFraction: 8_625,
      fractions: 10,
      periodStart: '2024-07-01T00:00:00.000Z',
      periodEnd: '2024-09-30T23:59:59.000Z',
      paymentDate: '2024-10-01T08:00:00.000Z',
      status: 'paid',
      createdAt: '2024-10-01T08:00:00.000Z',
      investment: {
        id: 'inv_001',
        asset: {
          id: 'asset_logistico_norte',
          name: 'Centro Logístico Santiago Norte',
        },
      },
    },
    {
      id: 'div_002',
      amount: 191_094,
      perFraction: 7_643.76,
      fractions: 25,
      periodStart: '2024-09-01T00:00:00.000Z',
      periodEnd: '2024-11-30T23:59:59.000Z',
      paymentDate: '2024-12-01T08:00:00.000Z',
      status: 'paid',
      createdAt: '2024-12-01T08:00:00.000Z',
      investment: {
        id: 'inv_002',
        asset: {
          id: 'asset_datacenter_vp',
          name: 'Micro Data Center Valparaíso',
        },
      },
    },
    {
      id: 'div_003',
      amount: 70_500,
      perFraction: 1_500,
      fractions: 47,
      periodStart: '2024-11-01T00:00:00.000Z',
      periodEnd: '2025-01-31T23:59:59.000Z',
      paymentDate: undefined,
      status: 'pending',
      createdAt: '2025-01-15T08:00:00.000Z',
      investment: {
        id: 'inv_003',
        asset: {
          id: 'asset_ecommerce_maipu',
          name: 'Bodega E-Commerce Maipú Hub',
        },
      },
    },
    {
      id: 'div_004',
      amount: 86_250,
      perFraction: 8_625,
      fractions: 10,
      periodStart: '2024-10-01T00:00:00.000Z',
      periodEnd: '2024-12-31T23:59:59.000Z',
      paymentDate: '2025-01-15T08:00:00.000Z',
      status: 'paid',
      createdAt: '2025-01-15T08:00:00.000Z',
      investment: {
        id: 'inv_001',
        asset: {
          id: 'asset_logistico_norte',
          name: 'Centro Logístico Santiago Norte',
        },
      },
    },
  ],

  liquidityPool: {
    id: 'pool_001',
    totalReserve: 450_000_000,
    totalAssets: 6,
    activeRequests: 3,
    utilizationRate: 42.5,
    monthlyContribution: 15_000_000,
    autoReplenish: true,
  },

  notifications: [
    {
      id: 'notif_001',
      type: 'dividend',
      title: 'Dividendo Recibido',
      message: 'Has recibido $86.250 CLP de dividendos por tu inversión en Centro Logístico Santiago Norte.',
      read: false,
      createdAt: '2025-01-15T08:00:00.000Z',
    },
    {
      id: 'notif_002',
      type: 'system',
      title: 'Nuevo Activo Disponible',
      message: 'Se ha publicado un nuevo activo: Bodega E-Commerce Maipú Hub. ¡Invierte desde $120.000!',
      read: false,
      createdAt: '2025-01-14T10:00:00.000Z',
    },
    {
      id: 'notif_003',
      type: 'kyc',
      title: 'Verificación Completada',
      message: 'Tu verificación de identidad ha sido aprobada exitosamente. Ya puedes acceder a todas las funcionalidades de la plataforma.',
      read: true,
      createdAt: '2024-12-20T09:00:00.000Z',
    },
    {
      id: 'notif_004',
      type: 'investment',
      title: 'Inversión Confirmada',
      message: 'Tu compra de 47 fracciones en Bodega E-Commerce Maipú Hub ha sido procesada exitosamente.',
      read: true,
      createdAt: '2024-11-15T10:45:00.000Z',
    },
    {
      id: 'notif_005',
      type: 'system',
      title: 'Reporte Mensual Disponible',
      message: 'El reporte de rendimiento de noviembre 2024 ya está disponible en tu panel de inversiones.',
      read: true,
      createdAt: '2024-12-05T12:00:00.000Z',
    },
  ],

  totalDividends: 434_094,
  unreadNotifications: 2,
}
